CREATE TABLE rents
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  userId INTEGER NOT NULL,
  carId INTEGER NOT NULL UNIQUE,
  rentDate DATE NOT NULL,
  FOREIGN KEY (userId) REFERENCES users(id),
  FOREIGN KEY (carId) REFERENCES cars(id)
);